/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ERRORUNKNOWN;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-19T05:43:44.883Z")

@Api(value = "vehicles", description = "the vehicles API")
public interface VehiclesApi {

    @ApiOperation(value = "", nickname = "driveState", notes = "Returns the driving state of the vehicle", response = ERRORUNKNOWN.class, tags={ "Vehicle", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ERRORUNKNOWN.class) })
    @RequestMapping(value = "/vehicles/{id}/data_request/drive_state",
        method = RequestMethod.GET)
    ResponseEntity<ERRORUNKNOWN> driveState(@ApiParam(value = "The ID number of the vehicle",required=true) @PathVariable("id") String id);

}
